let deviceList = {
  type: "method",
  id: 0,
  route: "Device.list",
  code: 200,
  data: [
    {
      name: "e1-led",
      type: 0,
      detailsContent: "e1-led,rgb灯,控制颜色显示",
      inputType: 3,
      outputType: 1,
      controlType:2,
      controlRange: ["off", "on", "yello", "red", "white"],
      returnRange: [0, 1],
    },
    {
      name: "e1-display",
      type: 0,
      detailsContent: "e1-display,四位数码管,用于显示",
      inputType: 4,
      outputType: 1,
      controlType:3,
      controlRange: [0, 9],
      returnRange: [0, 1],
    },
    {
      name: "e2",
      type: 0,
      detailsContent: "e2-风扇,一个模拟的小风扇",
      inputType: 3,
      outputType: 1,
      controlType:2,
      controlRange: ["off", "on", "low", "medium", "hight"],
      returnRange: [0, 1],
    },
    {
      name: "e3",
      type: 0,
      detailsContent: "e3-窗帘机,用于模拟窗帘开关",
      inputType: 2,
      outputType: 1,
      controlType:3,
      controlRange: [0, 100],
      returnRange: [0, 1],
    },
    {
      name: "s1",
      type: 1,
      detailsContent: "s1按键子板,用于输入按钮信息",
      inputType: 0,
      outputType: 2,
      controlType:0,
      controlRange: [],
      returnRange: [1, 12],
    },
    {
      name: "s6",
      type: 1,
      detailsContent: "s6-超声波传感器,用于获取距离",
      inputType: 1,
      outputType: 2,
      controlType:3,
      controlRange: [0, 1],
      returnRange: [250, 16000000],
    },
    {
      name: "s7",
      type: 1,
      detailsContent: "s7-红外热释电,用于获取距离",
      inputType: 1,
      outputType: 1,
      controlType:3,
      controlRange: [0, 1],
      returnRange: [0, 1],
    },
  ],
};
let openLighting = {
  type: "method",
  id: 0,
  route: "Device.control",
  code: 200,
  data: {
    result: true,
  },
};

module.exports = { deviceList, openLighting };
